spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9001/oauth2/jwks
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  metrics:
    tags:
      application: ${spring.application.name}
