server:
  port: 9003
spring:
  application:
    name: cart-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    config:
      uri: http://localhost:8888
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
