server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:file:./deploy/config}
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,metrics,prometheus
